"""Added columns in user table

Revision ID: 4bbfd9b9c2a7
Revises: 63532f56720e
Create Date: 2025-11-19 13:49:35.824855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbfd9b9c2a7'
down_revision: Union[str, Sequence[str], None] = '63532f56720e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])
        batch_op.create_unique_constraint(None, ['stripe_subscription_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
